services:
  chrome-app:
    build: .
    image: musaspacecadet/chrome:alpine
    privileged: true
    environment:
      - DISPLAY=:99
      - LIBGL_ALWAYS_SOFTWARE=:1
    expose:
      - "5900" # VNC port
      - "5800" # WEB port
      - "8000" # API port
      - "9000-9100" # Chrome debugging ports
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - chrome_network

networks:
  chrome_network:
    driver: bridge
